### ISSUE TITLE
red5-hls plugin not able to build

### ISSUE THREAD

**Issue by Sharad001** [Red5/red5-hls-plugin#8]
[INFO] Scanning for projects...
[WARNING] POM for 'biz.aQute:bndlib:pom:1.50.0:runtime' is invalid.

Its dependencies (if any) will NOT be available to the current build.
[INFO] ------------------------------------------------------------------------
[INFO] Building hls-plugin
[INFO]    task-segment: [install]
[INFO] ------------------------------------------------------------------------
[INFO] [resources:resources {execution: default-resources}]
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] Copying 0 resource
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error building POM (may not be this project's POM).

Project ID: org:jaudiotagger

Reason: Error getting POM for 'org:jaudiotagger' from the repository: Unable to read local copy of metadata: Cannot read metadata from '/home/sharad/.m2/repository/org/jaudiotagger/2.0.4-SNAPSHOT/maven-metadata-sonatype-snapshots.xml': end tag name </body> must match start tag name <hr> from line 5 (position: TEXT seen ...</center>\r\n</body>... @6:8) 
  org:jaudiotagger:pom:2.0.4-SNAPSHOT

 for project org:jaudiotagger

[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1 second
[INFO] Finished at: Wed Jun 18 16:24:24 JST 2014
[INFO] Final Memory: 26M/216M
[INFO] ------------------------------------------------------------------------

**Comment by Perfect-Web** [comment]
i am not able to build this as well
